# ==============================================================
# = Authentication Server JWT
# ==============================================================
spring:
    application:
        name: AUTH-SERVICE
server:
    port: 9100

# ==============================================================
# = Parametri Servizio gestUser
# ==============================================================
gestuser:
  srvUrl: http://localhost:8019/api/utenti/cerca/userid/
  userId: ReadUser
  password: BimBumBam_2018

# ==============================================================
# = Parametri Sicurezza JWT 
# ==============================================================
sicurezza:
    uri: /auth
    refresh: /refresh
    header: Authorization
    prefix: Bearer 
    expiration: 600
    secret: $123_Stella@xantrix.it

# ==============================================================
# = Livello Log di Sicurezza
# ==============================================================  
logging:
  level:
    org:
      springframework:
        security: DEBUG


        

  
 